<a href="https://colab.research.google.com/github/omeredemen/pytorch-tutorial/blob/main/tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Tensors
- A torch. Tensor is a multi-dimensional matrix containing elements of a single data type
- Similar to numpy arrays
- default data type of float32
- more suitable for deep learning than a numpy array

In [1]:
import torch
import numpy as np

# Lists

In [2]:
my_list = [[1,2,3,4],[5,6,7,8,9]]
my_list

[[1, 2, 3, 4], [5, 6, 7, 8, 9]]

# Numpy Arrays

In [6]:
np1 = np.random.rand(2,2,3)
np1

array([[[0.17620732, 0.60945529, 0.2060304 ],
        [0.7755575 , 0.0706324 , 0.95408748]],

       [[0.13081171, 0.19192383, 0.39062238],
        [0.80955554, 0.33440815, 0.45007647]]])

In [7]:
np1.dtype

dtype('float64')

# Tensors

In [10]:
tens_2d = torch.randn(3,4)
tens_2d

tensor([[ 0.1530,  0.9822, -0.8382,  1.1041],
        [ 1.4207,  0.6965, -2.1902, -1.0228],
        [-0.6634,  0.3186, -0.3253,  1.5615]])

In [11]:
tens_3d = torch.zeros(2,3,4)
tens_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [12]:
tens_3d.dtype

torch.float32

In [13]:
tens_np = torch.tensor(np1)
tens_np

tensor([[[0.1762, 0.6095, 0.2060],
         [0.7756, 0.0706, 0.9541]],

        [[0.1308, 0.1919, 0.3906],
         [0.8096, 0.3344, 0.4501]]], dtype=torch.float64)