<a href="https://colab.research.google.com/github/omeredemen/pytorch-tutorial/blob/main/tensor_operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch

# Operations

In [3]:
my_torch = torch.arange(10)
my_torch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
#reshape() and view()
my_torch = my_torch.reshape(2,5)
my_torch

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [14]:
my_torch2 = torch.arange(12)
my_torch2

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [16]:
# if we dont know th number of items using -1
my_torch2 = my_torch2.reshape(3,-1)
my_torch2

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [17]:
my_torch3 = torch.arange(10)
my_torch3

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
my_torch4 = my_torch3.view(2,5)
my_torch4

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [22]:
my_torch5 = torch.arange(10)
my_torch5

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
my_torch6 = my_torch5.reshape(2,5)
my_torch6

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [24]:
# now we will update the my_torch6 through my_torch5 indexes
my_torch5[1] = 622
my_torch6

tensor([[  0, 622,   2,   3,   4],
        [  5,   6,   7,   8,   9]])

In [30]:
my_torch7 = torch.arange(10)
my_torch7

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
# grab a specific item
my_torch7[7]

tensor(7)

In [34]:
# grab slice
my_torch8 = my_torch7.reshape(5,2)
my_torch8

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [35]:
my_torch8[:,1]

tensor([1, 3, 5, 7, 9])

In [37]:
my_torch8[:1]

tensor([[0, 1]])

In [38]:
my_torch8[:1, 1]

tensor([1])

In [40]:
my_torch8[0,1]

tensor(1)

In [41]:
my_torch8[1,:]

tensor([2, 3])

In [47]:
my_torch9 = my_torch8.reshape(-1,5)
my_torch9

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [51]:
my_torch9[0,:]

tensor([0, 1, 2, 3, 4])

# Math Operations
- Add, substract, multiply, divide, reaminders, exponents
- shorthand and longhand
- reassignment

In [52]:
import numpy as np

In [56]:
ta = torch.tensor([1,2,3,4])
tb = torch.tensor([5,6,7,8])
print(ta)
print(tb)

tensor([1, 2, 3, 4])
tensor([5, 6, 7, 8])


In [57]:
# Addition
ta+tb

tensor([ 6,  8, 10, 12])

In [58]:
# Addition longhand
torch.add(ta,tb)

tensor([ 6,  8, 10, 12])

In [59]:
# Subtraction
ta - tb

tensor([-4, -4, -4, -4])

In [61]:
# subtraction Longhand
# sub() is same with subtract()
torch.sub(ta, tb)
torch.subtract(ta, tb)

tensor([-4, -4, -4, -4])

In [62]:
# Multiplication
ta * tb

tensor([ 5, 12, 21, 32])

In [63]:
torch.multiply(ta, tb)

tensor([ 5, 12, 21, 32])

In [66]:
# Division
ta / tb

tensor([0.2000, 0.3333, 0.4286, 0.5000])

In [67]:
torch.divide(ta,tb)

tensor([0.2000, 0.3333, 0.4286, 0.5000])

In [69]:
# Remainder
ta % tb

tensor([1, 2, 3, 4])

In [70]:
torch.remainder(ta,tb)

tensor([1, 2, 3, 4])

In [72]:
# Power
ta ** tb

tensor([    1,    64,  2187, 65536])

In [73]:
torch.pow(ta,tb)

tensor([    1,    64,  2187, 65536])

In [75]:
# annother way to add
ta.add(tb)

tensor([ 6,  8, 10, 12])

In [78]:
# Reassignment
# ta = ta + tb
ta.add_(tb)

tensor([11, 14, 17, 20])

In [79]:
ta

tensor([11, 14, 17, 20])